export const salesData = [
  {
    id: 1,
    name: "죽전역 해링턴 플레이스 더 베스트",
    category: "아파트, 오피스텔, 근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_01.png",
    location: "대구 달서구 감삼동 567-1",
    houseHoldSum: "200세대, 46호실, 20호실",
    scale: "지하4층/ 지상45층",
  },
  {
    id: 2,
    name: "죽전역 해링턴 플레이스 더 원",
    category: "아파트, 오피스텔, 근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_02.png",
    location: "대구 달서구 와룡로31길 16",
    houseHoldSum: "200세대, 120호실, 20호실",
    scale: "지하4층/ 지상65층",
  },
  {
    id: 3,
    name: "수성 알파시티 대경 엘리시아",
    category: "오피스텔, 근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_03.png",
    location: "대구 수성구 알파시티1로42길 24",
    houseHoldSum: "42호실, 19호실",
    scale: "지하2층/ 지상5층",
  },
  {
    id: 4,
    name: "힐스에비뉴 동인 센트럴",
    category: "근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_04.png",
    location: "대구 중구동1가 235-1",
    houseHoldSum: "25호실",
    scale: "지하4층/ 지상48층",
  },
  {
    id: 5,
    name: "설화명곡역 우방아이유쉘",
    category: "근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_05.png",
    location: "대구 달성군 비슬로 2417",
    houseHoldSum: "25호실",
    scale: "지하2층/ 지상29층",
  },
  {
    id: 6,
    name: "화원 동화 아이위시",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_06.png",
    location: "대구 달성군 비슬로508길 1",
    houseHoldSum: "105호실",
    scale: "지하2층/ 지상41층",
  },
  {
    id: 7,
    name: "센트럴 대원 칸타빌",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_07.png",
    location: "대구 중구 동인동1가",
    houseHoldSum: "44호실",
    scale: "지하4층/ 지상43층",
  },
  {
    id: 8,
    name: "펜타플렉스 부산",
    category: "지식산업센터, 근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_08.png",
    location: "부산 사하구 장림번영로 77",
    houseHoldSum: "411호실, 22호실",
    scale: "지하1층/ 지상15층",
  },
  {
    id: 9,
    name: "경산 샤갈의 마을",
    category: "연립주택",
    img: process.env.PUBLIC_URL + "/images/sales_09.png",
    location: "경북 경산시 삼성현로 614-5",
    houseHoldSum: "32세대",
    scale: "지하2층/ 지상4층",
  },
  {
    id: 10,
    name: "태왕 The아너스 오페라",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_10.png",
    location: "대구 북구 고성동1가 162-11",
    houseHoldSum: "66호실",
    scale: "지하4층/ 지상49층",
  },
  {
    id: 11,
    name: "힐스테이트 대구역",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_11.png",
    location: "대구 중구 태평로28길 13",
    houseHoldSum: "150호실",
    scale: "지하4층/ 지상29층",
  },
  {
    id: 12,
    name: "힐스테이트 동인 센트럴",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_12.png",
    location: "대구 중구 동인동1가 235-20",
    houseHoldSum: "25호실",
    scale: "지하4층/ 지상48층",
  },
  {
    id: 13,
    name: "대구역 SD아이프라임",
    category: "아파트, 오피스텔, 근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_13.png",
    location: "대구 북구 칠성동2가 302-197",
    houseHoldSum: "80세대, 15호실, 10호실",
    scale: "지하2층/ 지상24층",
  },
  {
    id: 14,
    name: "경산 중산타워",
    category: "근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_14.png",
    location: "경북 경산시 펜타힐즈2로 27",
    houseHoldSum: "44호실",
    scale: "지하1층/ 지상9층",
  },
  {
    id: 15,
    name: "반월당역 클래시아 2차",
    category: "근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_15.png",
    location: "대구 중구 봉산동 50",
    houseHoldSum: "22호실",
    scale: "지하4층/ 지상20층",
  },
  {
    id: 16,
    name: "대구 오페라 클래시아 3차",
    category: "대구 북구 칠성동2가 296-2",
    img: process.env.PUBLIC_URL + "/images/sales_16.png",
    location: "대구 중구 봉산동 50",
    houseHoldSum: "596호실, 46호실",
    scale: "지하4층/ 지상21층",
  },
  {
    id: 17,
    name: "침산 시그니처 타워",
    category: "근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_17.png",
    location: "대구 북구 침산동 341-4",
    houseHoldSum: "44호실",
    scale: "지하1층/ 지상9층",
  },
  {
    id: 18,
    name: "김천 탑 클래스",
    category: "근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_18.png",
    location: "경북 김천시 율곡동 791",
    houseHoldSum: "41호실",
    scale: "지하1층/ 지상5층",
  },
  {
    id: 19,
    name: "그루메디타워",
    category: "근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_19.png",
    location: "대구 달서구 월성동 1811",
    houseHoldSum: "35호실",
    scale: "지하1층/ 지상8층",
  },
  {
    id: 20,
    name: "신월성 미래타워",
    category: "근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_20.png",
    location: "대구 달서구 월성동 1859",
    houseHoldSum: "42호실",
    scale: "지하1층/ 지상8층",
  },
  {
    id: 21,
    name: "MH엘퍼스트 오페라",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_21.png",
    location: "대구 북구 침산동 1-2",
    houseHoldSum: "396호실",
    scale: "지하3층/ 지상20층",
  },
  {
    id: 22,
    name: "서한 코보스카운티",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_22.png",
    location: "대구 동구 신천동 285-1",
    houseHoldSum: "193호실",
    scale: "지하2층/ 지상20층",
  },
  {
    id: 23,
    name: "수성 퍼플하임",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_23.png",
    location: "대구 북구 침산동 1-2",
    houseHoldSum: "193호실",
    scale: "지하4층/ 지상14층",
  },
  {
    id: 24,
    name: "김천 코아루 파크드림시티",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_24.png",
    location: "경북 김천시 혁신1로 58",
    houseHoldSum: "396호실",
    scale: "지하3층/ 지상26층",
  },
  {
    id: 25,
    name: "제주 글로스터호텔(구.하워드존슨)",
    category: "숙박시설(호텔)",
    img: process.env.PUBLIC_URL + "/images/sales_25.png",
    location: "제주 제주시 삼무로 57",
    houseHoldSum: "464호실",
    scale: "지하4층/ 지상18층",
  },
  {
    id: 26,
    name: "울산 프리지아",
    category: "근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_26.png",
    location: "울산 북구 신답로 48",
    houseHoldSum: "66호실",
    scale: "지하1층/ 지상4층",
  },
  {
    id: 27,
    name: "푸드 애비뉴",
    category: "근린생활시설",
    img: process.env.PUBLIC_URL + "/images/sales_27.png",
    location: "대구 동구 동내동 1121",
    houseHoldSum: "41호실",
    scale: "지하2층/ 지상10층",
  },
  {
    id: 28,
    name: "파크드림시티 써밋",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_28.png",
    location: "경북 김천시 혁신1로 75",
    houseHoldSum: "736호실",
    scale: "지하2층/ 지상25층",
  },
  {
    id: 29,
    name: "속초 라마다호텔",
    category: "생활형 숙박시설",
    img: process.env.PUBLIC_URL + "/images/sales_29.png",
    location: "강원 속초시 대포항희망길 106",
    houseHoldSum: "552호실",
    scale: "지하2층/ 지상20층",
  },
  {
    id: 30,
    name: "청라 딜라이트타워 2차",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_30.png",
    location: "인천 서구 청라에메랄드로 84",
    houseHoldSum: "265호실",
    scale: "지하4층/ 지상20층",
  },
  {
    id: 31,
    name: "동대구 유성푸르나임",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_31.png",
    location: "대구 동구 동부로22길 48",
    houseHoldSum: "821호실",
    scale: "지하4층/ 지상20층",
  },
  {
    id: 32,
    name: "미래시티빌",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_32.png",
    location: "부산 남구 전포대로92번길 7",
    houseHoldSum: "89호실",
    scale: "지하1층/ 지상15층",
  },
  {
    id: 33,
    name: "파밀리에 펄시티",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_33.png",
    location: "부산 해운대구 좌동 1459-2",
    houseHoldSum: "630호실",
    scale: "지하5층/ 지상24층",
  },
  {
    id: 34,
    name: "인터불고 코아시스",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_34.png",
    location: "대구 중구 명륜로 19",
    houseHoldSum: "192호실",
    scale: "지하1층/ 지상17층",
  },
  {
    id: 35,
    name: "죽전 한양 아이클래스",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_35.png",
    location: "부산 남구 전포대로92번길 7",
    houseHoldSum: "372호실",
    scale: "지하2층/ 지상20층",
  },
  {
    id: 36,
    name: "범어 세비앙",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_36.png",
    location: "대구 수성구 동대구로59길 14-2",
    houseHoldSum: "98호실",
    scale: "지하2층/ 지상8층",
  },
  {
    id: 37,
    name: "국채보상공원 화성파크드림시티",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_37.png",
    location: "대구 중구 국채보상로 655",
    houseHoldSum: "982호실",
    scale: "지하4층/ 지상29층",
  },
  {
    id: 38,
    name: "광교 에듀하임 1309",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_38.png",
    location: "경기 수원시 영통구 에듀타운로 101",
    houseHoldSum: "1,309호실",
    scale: "지하3층/ 지상15층",
  },
  {
    id: 39,
    name: "동탄 메트로하임",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_39.png",
    location: "경기 화성시 메타폴리스로 47-25",
    houseHoldSum: "418호실",
    scale: "지하3층/ 지상26층",
  },
  {
    id: 40,
    name: "서후 센타시아",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_40.png",
    location: "인천 서구 중봉대로612번길 16",
    houseHoldSum: "226호실",
    scale: "지하6층/ 지상14층",
  },
  {
    id: 41,
    name: "상암 월드시티",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_41.png",
    location: "서울 마포구 월드컵로34길 13 상암",
    houseHoldSum: "325호실",
    scale: "지하5층/ 지상15층",
  },
  {
    id: 42,
    name: "청라 매그놀리아",
    category: "오피스텔",
    img: process.env.PUBLIC_URL + "/images/sales_42.png",
    location: "인천 서구 중봉대로586번길 9-11",
    houseHoldSum: "249호실",
    scale: "지하4층/ 지상10층",
  },
];

export const promotionData = [
  {
    id: 1,
    name: "해링턴 플레이스 감삼 더 베스트",
    category: "근린생활시설",
    map: {
      center: {
        lat: 35.8477,
        lng: 128.5349,
      },
      bounds: [
        {
          lat: 35.84795,
          lng: 128.53483,
        },
        {
          lat: 35.84798,
          lng: 128.5347,
        },
        {
          lat: 35.847859,
          lng: 128.5346,
        },
        {
          lat: 35.84772,
          lng: 128.53447,
        },
        {
          lat: 35.847661,
          lng: 128.53447,
        },
        {
          lat: 35.84764,
          lng: 128.5345,
        },
        {
          lat: 35.8474,
          lng: 128.5351,
        },
        {
          lat: 35.84731,
          lng: 128.5354,
        },
        {
          lat: 35.84745,
          lng: 128.53549,
        },

        {
          lat: 35.847727,
          lng: 128.535302,
        },

        {
          lat: 35.84785,
          lng: 128.5349949,
        },
      ],
    },
    image: process.env.PUBLIC_URL + "/images/sales_01.png",
    pyeng: [
      {
        type: "default",
        image: process.env.PUBLIC_URL + "/images/pyeng_01_default.png",
        pricePerRoom: [29200, 191000],
        areaPrice: [1503, 3964],
      },
    ],
    homepage: "http://harrington-mh5.com",
    fileLink:
      "https://www.dalseo.daegu.kr/resource/sn3hcv/skin/doc.html?fn=BBS_202301180635291270&rs=/resource/sn3hcv/preview/202402/",
    location: "대구 달서구 감삼동 567-1",
    phone: "1644-6601",
    houseHoldSum: "20호실",
    inDate: "2024-05",
    status: "completed",
  },
  {
    id: 2,
    name: "죽전역 해링턴 플레이스 더 원",
    category: "아파트, 오피스텔, 근린생활시설",
    map: {
      center: {
        lat: 35.8469,
        lng: 128.5352,
      },
      bounds: [
        {
          lat: 35.8473867,
          lng: 128.534962,
        },
        {
          lat: 35.8469951,
          lng: 128.5349712,
        },
        {
          lat: 35.8465716,
          lng: 128.5347262,
        },
        {
          lat: 35.8465489,
          lng: 128.5353645,
        },
        {
          lat: 35.8471175,
          lng: 128.5356501,
        },
      ],
    },
    image: process.env.PUBLIC_URL + "/images/sales_02.png",
    pyeng: [
      {
        type: "근린생활시설",
        image: process.env.PUBLIC_URL + "/images/pyeng_02_default.png",
        pricePerRoom: [24600, 94000],
        areaPrice: [1842, 3954],
      },
      {
        type: "84OA",
        image: process.env.PUBLIC_URL + "/images/pyeng_02_84OA.png",
        price: [41300, 42700],
      },
      {
        type: "84OB",
        image: process.env.PUBLIC_URL + "/images/pyeng_02_84OB.png",
        price: [41300, 42700],
      },
      {
        type: "84OC",
        image: process.env.PUBLIC_URL + "/images/pyeng_02_84OC.png",
        price: [41300, 42700],
      },
    ],
    location: "대구 달서구 와룡로31길 16",
    fileLink:
      "https://www.dalseo.daegu.kr/resource/sn3hcv/skin/doc.html?fn=BBS_202301180634200270&rs=/resource/sn3hcv/preview/202402/",
    phone: "1644-6601",
    houseHoldSum: "120호실, 20호실",
    inDate: "2023-05",
    status: "inspected",
  },
  {
    id: 3,
    name: "이곡 라온하제",
    category: "근린생활시설",
    map: {
      center: {
        lat: 35.85427,
        lng: 128.50905,
      },
      bounds: [
        {
          lat: 35.8541826,
          lng: 128.5092312,
        },
        {
          lat: 35.8541865,
          lng: 128.5089116,
        },

        {
          lat: 35.8543741,
          lng: 128.5089168,
        },
        {
          lat: 35.85436,
          lng: 128.50914,
        },
        {
          lat: 35.8543368,
          lng: 128.50914,
        },
        {
          lat: 35.8543324,
          lng: 128.5092331,
        },
      ],
    },
    image: process.env.PUBLIC_URL + "/images/sales_43.png",
    pyeng: [
      {
        type: "default",
        image: process.env.PUBLIC_URL + "/images/pyeng_03_default.png",
        pricePerRoom: [33257, 102179],
        areaPrice: [1020, 3480],
      },
    ],
    location: "대구 달서구 이곡동 1246-5",
    phone: "1544-7493",
    houseHoldSum: "57호실",
    inDate: "2023-07",
    status: "inspected",
  },
  {
    id: 4,
    name: "힐스에비뉴 동인 센트럴",
    category: "근린생활시설",
    map: {
      center: {
        lat: 35.87118,
        lng: 128.6036,
      },
      bounds: [
        {
          lat: 35.87142,
          lng: 128.60425,
        },
        {
          lat: 35.87063,
          lng: 128.60411,
        },
        {
          lat: 35.870925,
          lng: 128.60277,
        },
        {
          lat: 35.8715425,
          lng: 128.6029204,
        },
      ],
    },
    image: process.env.PUBLIC_URL + "/images/sales_04.png",
    pyeng: [
      {
        type: "근린생활시설",
        image: process.env.PUBLIC_URL + "/images/pyeng_04_default.png",
        pricePerRoom: [29200, 191000],
        areaPrice: [1503, 3964],
      },
    ],
    location: "대구 중구동1가 235-1",
    fileLink:
      "https://www.jung.daegu.kr/new/Preview/202404/36bc7531aa1b5ab0943795a58f05de3b.htm",
    phone: "053-710-7088",
    houseHoldSum: "25호실",
    scale: "지하4층/ 지상48층",
    inDate: "2024-04 ",
    status: "completed",
  },
];
